### PR TITLE
fixed php 8 problem

### PR DESCRIPTION
**Pull request by t-schroeder**
This fixes an error that you'd get when opening a thread so that a "pin" button appears.

> Required parameter $pinlink follows optional parameter $method

### CODE REVIEW

**Comment by cameron1729** [comment]
I would recommend against changing the param order as it breaks backwards compatibility. Instead just make `$pinlink` and `$discussion` optional.

**Comment by t-schroeder** [comment]
May I ask backwards compatibility with what? The function is defined and used in this plugin.

There's no such thing as a (valid) default discussion ID. Wouldn't that only make it confusing for people working with this in the future (making a parameter optional that's not optional)?

**Comment by cameron1729** [comment]
Sorry, I made the wrong suggestion here. The better choice is to make `$method` **not optional** as it's impossible for `render_ax_button` to have been called without providing a value for `$method`.  This way parameter orders are not changed, and no calling code has to be modified. Which also means the changes required in your own plugin are fewer too.

When I say backwards compatible, I mean that the visibility of the `render_ax_button` is `public`. Meaning that it's possible that someone could be calling it from their own plugin (even if this is not the intention). If you change the parameter order, then someone upgrades to the newer version of your plugin, another plugin in their system could potentially break.

**Comment by t-schroeder** [comment]
Closing this since the issue has already been fixed.

**Pull request closed without merging**
